@startuml
[*] --> AtFloor

AtFloor --> DoorOpen : / OpenDoor
DoorOpen --> DoorOpen : PollObstruct / Restart timer
DoorOpen --> DoorClosed : wait 3s
DoorClosed --> Moving : [RequestToConsume] / ConsumeRequest

Moving --> AtFloor: PollFloorSensor == GoingToFloor / UpdateIndicators
Moving --> Moving: PollFloorSensor != GoingToFloor / UpdateIndicators

AtFloor --> EmergencyStop : PollStop / ResetQueue & OpenDoor
DoorOpen --> EmergencyStop : PollStop / ResetQueue
DoorClosed --> EmergencyStop : PollStop / ResetQueue
Moving --> EmergencyStop : PollStop / ResetQueue
EmergencyStop --> DoorOpen : NoPollStop [AtFloor] / OpenDoor
EmergencyStop --> DoorClosed : NoPollStop [NotAtFloor]


@enduml